<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schemansv="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hal_buddy</name>
  <version>0.1.0</version>
  <description>BUDDY HAL node with simulated data</description>
  <maintainer email="poc@robotics.lab">POC Team</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>hal_interface</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>